name: Test - Modules
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10, 12]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: setup node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install modules
      run: >-
        OTPLIB_SETUP_COMMON=true
        OTPLIB_SETUP_EXTRAS=skip
        npm run setup

    - name: install extras
      if: matrix.node-version > 8
      run: >-
        OTPLIB_SETUP_COMMON=false
        OTPLIB_SETUP_EXTRAS=testmodule
        npm run setup

    - name: build packages
      run: >-
        OTPLIB_BUILD_CLEAN=true
        OTPLIB_BUILD_MODULE=true
        OTPLIB_BUILD_BUNDLE=true
        OTPLIB_BUILD_DOWNLOAD_BUFFER=false
        OTPLIB_BUILD_COPY_META=false
        npm run build

    - name: sanity test for node <= 8
      if: matrix.node-version <= 8
      run: npm run test:node8

    - name: full test for node > 8
      if: matrix.node-version > 8
      run: npm run test:module


