name: Build and Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: node version - ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install modules
      run: npm ci
    - name: build packages
      run: npm run build:ci
    - name: test
      run: npm run test
