name: Test - Browser
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: install modules
      run: >-
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
        OTPLIB_SETUP_COMMON=true
        OTPLIB_SETUP_EXTRAS=testbrowser
        npm run setup

    - name: build packages
      run: >-
        OTPLIB_BUILD_CLEAN=true
        OTPLIB_BUILD_MODULE=false
        OTPLIB_BUILD_BUNDLE=true
        OTPLIB_BUILD_DOWNLOAD_BUFFER=true
        OTPLIB_BUILD_COPY_META=false
        npm run build

    - name: test
      uses: docker://buildkite/puppeteer:v1.15.0
      with:
        args: npm run test:browser


